-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
    {
        "bjarneo/pixel.nvim",
        name = "pixel",
    },
    {
        "LazyVim/LazyVim",
        opts = {
            colorscheme = "pixel",
        },
    },
}