# Monitor configuration
# See https://wiki.hyprland.org/Configuring/Monitors/

env = GDK_SCALE,1

# Laptop internal screen (1080p @ 60Hz)
monitor = eDP-1, preferred, 0x0, 1.25

# External 1440p monitor (Iiyama 2560x1440 @ 75Hz, crisp 1:1 scale)
monitor = HDMI-A-1, 2560x1440@74.92, auto, 1

# Fallback for any other external display:
monitor = , highrr, auto, 1
