# Monitor configuration
# See https://wiki.hyprland.org/Configuring/Monitors/

# Built-in laptop display:
monitor = eDP-1, preferred, 0x0, 1.25

# Universal rule for external display:
monitor = , preferred, auto-right, 1
