# ────────────────────────────────────────────────────────────
# Omarchy Custom Theme for btop
# Generated with Omarchist
# ────────────────────────────────────────────────────────────

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0D0D0D"

# Main text color
theme[main_fg]="#ebdbb2"

# Title color for boxes
theme[title]="#6E6A58"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f5bf03"

# Background color of selected item in processes box
theme[selected_bg]="#a3850e"

# Foreground color of selected item in processes box
theme[selected_fg]="#0D0D0D"

# Color of inactive/disabled text
theme[inactive_fg]="#5b4a08"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f5bf03"

# Cpu box outline color
theme[cpu_box]="#483b06"

# Memory/disks box outline color
theme[mem_box]="#483b06"

# Net up/down box outline color
theme[net_box]="#483b06"

# Processes box outline color
theme[proc_box]="#483b06"

# Box divider line and small boxes line color
theme[div_line]="#483b06"

# Temperature graph colors
theme[temp_start]="#ebdbb2"
theme[temp_mid]="#5b4a08"
theme[temp_end]="#D35F5F"

# CPU graph colors
theme[cpu_start]="#ebdbb2"
theme[cpu_mid]="#5b4a08"
theme[cpu_end]="#f5bf03"

# Mem/Disk free meter
theme[free_start]="#ebdbb2"
theme[free_mid]="#5b4a08"
theme[free_end]="#f5bf03"

# Mem/Disk cached meter
theme[cached_start]="#ebdbb2"
theme[cached_mid]="#5b4a08"
theme[cached_end]="#f5bf03"

# Mem/Disk available meter
theme[available_start]="#ebdbb2"
theme[available_mid]="#5b4a08"
theme[available_end]="#f5bf03"

# Mem/Disk used meter
theme[used_start]="#ebdbb2"
theme[used_mid]="#5b4a08"
theme[used_end]="#f5bf03"

# Download graph colors
theme[download_start]="#ebdbb2"
theme[download_mid]="#5b4a08"
theme[download_end]="#f5bf03"

# Upload graph colors
theme[upload_start]="#ebdbb2"
theme[upload_mid]="#5b4a08"
theme[upload_end]="#f5bf03"
